import '../../app/globals.css'
import { Inter } from 'next/font/google'
import Header from '@/app/(main)/components/Header'
import Footer from '@/app/(main)/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Header />
        <main className="flex-1 container py-5">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
